import React from 'react';

function AboutMe() {
    return (
        <div>
            <div className='titleSection'>
                <h1 className='pageTitle'>ABOUT ME</h1>
                <div className='meImageContainer'>
                    <img 
                        className='meImage'
                        src={require("../media/aboutMe/IMG_5071.jpeg")}
                        alt='alex catena' />
                </div>
                <div className='bio'>
                    <p>
                    My name is Alexandra Catena and I am a teacher who won a grant to travel through Italy! My grant title was “Confessions of an Appassionata”- and I was looking to find renewal through the exploration of my heritage by traveling across the various regions of Italy and documenting the journey in an Instagram/TikTok series that showcases the passion and beauty of the Italian people and culture.  As an Italian-American, I have always been drawn to my father’s homeland. After my family moved to America when I was young, they made every effort to keep our family entrenched in Italian customs, traditions, culture, and language. I have since found the most renewal of my spirit being in Italy and yearn to go back often. If it were up to me, I would move there tomorrow!"
                    <br></br><br></br>
                    The grant that I won is aimed at keeping teachers in the classroom through giving them time and money to find renewal and inspiration outside of the classroom. When I think about renewal, I think of the Renaissance—with its genesis in Italy. The renaissance or rebirth of great Roman and Greek art, literature, theater, etc., came after a period of immense darkness and plague, marked by years of hardship and suffering across Europe. The Renaissance and the humanist movement, largely started by Francis Petrarch (a native Italian), was started by one man deciding that he wanted to take control of his life and change his times by creating remarkable ideas and shifting/inspiring the narrative of humanity as it was known to the world. His passions inspired those around him and shifted an entire generation into a new creative paradigm. Renewal and regeneration are essential for an individual’s growth and a personal renaissance is imperative for me as a creative and passion person—an appassionata.
                    <br></br><br></br>
                    Being a passionate person or an appassionata is a double edge sword, because passion is both the fire that drives everything in my life forward while also being the flame that could burn everything to the ground. Passion is both exciting and exhausting, it is both rejuvenating and depleting, but passion is in the core makeup of an Italian and asking an Italian to temper their passion is like asking them to talk without their hands—it’s impossible. Recently, when I was reading this book called La Passione, by Dianne Hales, a book that both inspired the title of this project and also inspired me to explore my heritage more, I read a quote that resonated deeply with me, it is that “we do not choose our passion. Passion chooses us. Teaching is my passion and teaching content that excites me, that implores my cultural roots, is something that keeps me wanting to innovate.
                    <br></br><br></br>
                    I have been teaching for seven years, and in those seven years, I have endured more than educators with many more years of experience.  From working at my school while it served as a shelter during Hurricane Irma, to the Parkland shooting that same year in my home state, to the COVID pandemic, and so many more incidents—there are only so many “Once in a lifetime” events that anyone can handle without feeling burnt out. All of this whilst I, myself, am growing as a person and professional. Going through early adulthood, getting engaged, completing a master’s program while working full-time, planning, a wedding, canceling that wedding because of Covid, having a baby, the extreme juxtapositions of the past six years is not lost on me—and it’s exhausting. Teaching through the pandemic was the most draining experience I have ever experienced, and the pressure and uncertainty caused me so much anxiety and angst. 2020-2022 has been hard for everyone, but I truly feel like personally, as a young person in their twenties, I lost major formative years of personal growth. My husband and I had to make the difficult decision to cancel our dream wedding in my native Italy that we had been planning for two years, we were forced to cancel our dream honeymoon through Italy that I had thoroughly planned and that we had saved and planned for during that time, and we instead were forced to completely re-imagine our futures from the safety of our couch. Being pregnant during this uncertain time also forced me further into isolation for the safety of my son—and I am just drained emotionally and physically.
                    <br></br><br></br>
                    This summer was my Renaissance. I feel rebirth as a mother, as a woman, as a professional and I have a renewed sense of love and inspiration—of passion— for my son to take him back to my native Italy and expose him to his cultural roots while learning and exploring with him. Exploring deeply my Italian heritage and culture is more important to me now, more than ever, after having a baby; I want to be able to show and teach him about his people. I felt and continue to feel inspired to travel again and to explore the world that I have been watching through my window for the past couple of years with covid and pregnancy. I am no longer scared of the future, but excited. Reflection is at the core of passion because passion requires insight, it requires an engine that drives you, and reflection on my past, on my family’s past, will help drive my life and my son’s life into his future. Teaching literature and the arts, I make it a point to incorporate the art of storytelling and self-exploration through my curriculum and taking this trip would be incredibly inspiring for shaping my curriculum and learning more to bring back to my students. Travel enhances the foundation that the classroom provides.
                    </p>
                </div>
            </div>
        </div>
    );
}

export default AboutMe;